# Generated by Django 6.0.6 on 2026-07-07 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('nome_informado', models.CharField(help_text='Nome digitado por quem executou a ação.', max_length=150, verbose_name='Nome informado')),
                ('acao', models.CharField(choices=[('ENABLE', 'Ativar'), ('DISABLE', 'Desativar')], max_length=10, verbose_name='Ação')),
                ('status_anterior', models.CharField(blank=True, max_length=20, verbose_name='Status anterior')),
                ('status_final', models.CharField(blank=True, max_length=20, verbose_name='Status final')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário (login)')),
            ],
            options={
                'verbose_name': 'Log da Trigger',
                'verbose_name_plural': 'Logs da Trigger',
                'ordering': ['-criado_em'],
            },
        ),
    ]
