# Generated by Django 6.0.6 on 2026-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtrigger',
            name='motivo',
            field=models.CharField(blank=True, default='', help_text='Motivo informado por quem executou a ação.', max_length=255, verbose_name='Motivo'),
        ),
    ]
