# Generated by Django 6.0.6 on 2026-07-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logtrigger_motivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logtrigger',
            options={'ordering': ['-criado_em'], 'permissions': [('pode_operar_trava', 'Pode travar e destravar'), ('pode_ver_logs', 'Pode ver os logs')], 'verbose_name': 'Log da Trigger', 'verbose_name_plural': 'Logs da Trigger'},
        ),
    ]
