# Generated by Django 6.0.6 on 2026-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logtrigger_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtrigger',
            name='hostname',
            field=models.CharField(blank=True, default='', help_text='Nome da máquina de origem (DNS reverso do IP, quando disponível).', max_length=255, verbose_name='Hostname de origem'),
        ),
    ]
